// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
	settingGet: (key: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("setting_get", { key })),
	settingSet: (key: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("setting_set", { key, value })),
	activityList: (includeArchived: boolean) => typedError<Activity[], CommandError>(__TAURI_INVOKE("activity_list", { includeArchived })),
	activityUpsert: (input: ActivityInput) => typedError<Activity, CommandError>(__TAURI_INVOKE("activity_upsert", { input })),
	activityArchive: (id: string, archived: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("activity_archive", { id, archived })),
	/**  Persists a new order; `ids` lists activities top to bottom. */
	activityReorder: (ids: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("activity_reorder", { ids })),
	/**  Live sessions on this activity and its sub-activities; non-zero means it can only be archived. */
	activityUsage: (id: string) => typedError<number, CommandError>(__TAURI_INVOKE("activity_usage", { id })),
	/**  Deletes an activity without sessions (with its sub-activities and plans). Ask the user first. */
	activityDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("activity_delete", { id })),
	sessionStart: (activityId: string) => typedError<Session, CommandError>(__TAURI_INVOKE("session_start", { activityId })),
	sessionPause: () => typedError<{
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
	/**  Set when the session was logged automatically from a recurring plan. */
	plan_id: string | null,
} | null, CommandError>(__TAURI_INVOKE("session_pause")),
	sessionResume: () => typedError<Session, CommandError>(__TAURI_INVOKE("session_resume")),
	sessionStop: () => typedError<{
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
	/**  Set when the session was logged automatically from a recurring plan. */
	plan_id: string | null,
} | null, CommandError>(__TAURI_INVOKE("session_stop")),
	sessionCurrent: () => typedError<TimerState, CommandError>(__TAURI_INVOKE("session_current")),
	/**  Sessions overlapping the range, including a running one. */
	sessionList: (range: TimeRange) => typedError<Session[], CommandError>(__TAURI_INVOKE("session_list", { range })),
	sessionUpsert: (input: SessionInput) => typedError<Session, CommandError>(__TAURI_INVOKE("session_upsert", { input })),
	sessionDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("session_delete", { id })),
	/**  Saves every segment of an edited record at once; an overlap anywhere saves nothing. */
	sessionSave: (inputs: SessionInput[]) => typedError<Session[], CommandError>(__TAURI_INVOKE("session_save", { inputs })),
	/**  Deletes every segment of a record. Ask the user first. */
	sessionDeleteMany: (ids: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("session_delete_many", { ids })),
	traySetStrings: (strings: TrayStrings) => __TAURI_INVOKE<void>("tray_set_strings", { strings }),
	/**  Shows the tray's timer menu below the main window's timer button (logical px). */
	timerMenuPopup: (x: number, y: number) => typedError<null, CommandError>(__TAURI_INVOKE("timer_menu_popup", { x, y })),
	overlayShow: () => typedError<null, CommandError>(__TAURI_INVOKE("overlay_show")),
	overlayHide: () => typedError<null, CommandError>(__TAURI_INVOKE("overlay_hide")),
	/**  `true` lifts the overlay so it can be dragged; `false` saves the position and sinks it back. */
	overlaySetEditing: (editing: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("overlay_set_editing", { editing })),
	overlayResetPosition: () => typedError<null, CommandError>(__TAURI_INVOKE("overlay_reset_position")),
	/**  Called by the overlay page whenever its cards move or resize. */
	overlayLayout: (cards: CardFrame[]) => typedError<null, CommandError>(__TAURI_INVOKE("overlay_layout", { cards })),
	/**  One-off plans in the range plus recurring plans that have started; the frontend expands occurrences. */
	planList: (range: DateRange) => typedError<Plan[], CommandError>(__TAURI_INVOKE("plan_list", { range })),
	planUpsert: (input: PlanInput) => typedError<Plan, CommandError>(__TAURI_INVOKE("plan_upsert", { input })),
	planDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("plan_delete", { id })),
	/**
	 *  Logs recurring-plan occurrences that have ended (the page sends today's and the past 30 days').
	 *  Returns how many sessions were created.
	 */
	planAutolog: (occurrences: Occurrence[]) => typedError<number, CommandError>(__TAURI_INVOKE("plan_autolog", { occurrences })),
	journalList: (range: DateRange) => typedError<Journal[], CommandError>(__TAURI_INVOKE("journal_list", { range })),
	/**  Saves the day's entry; blank text removes it and returns `null`. */
	journalUpsert: (date: string, text: string) => typedError<{
	id: string,
	date: string,
	text: string,
} | null, CommandError>(__TAURI_INVOKE("journal_upsert", { date, text })),
	journalDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("journal_delete", { id })),
	/**  Opens a save panel (attached to the window) and writes every live record. `None` if cancelled. */
	dataExport: (defaultName: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("data_export", { defaultName })),
	/**  Opens a file panel and merges the chosen export into the database. `None` if cancelled. */
	dataImport: () => typedError<{
	activity: TableCounts,
	session: TableCounts,
	plan: TableCounts,
	journal: TableCounts,
	day: TableCounts,
} | null, CommandError>(__TAURI_INVOKE("data_import")),
	/**  Clears all records after saving a JSON backup to the Downloads folder. Returns the backup path. */
	dataWipe: (confirmation: string, backupName: string) => typedError<string, CommandError>(__TAURI_INVOKE("data_wipe", { confirmation, backupName })),
	dayList: (range: DateRange) => typedError<Day[], CommandError>(__TAURI_INVOKE("day_list", { range })),
	/**  Sets both times of a day by hand (editing the ring's end labels, undoing sleep). */
	daySet: (input: DayInput) => typedError<Day, CommandError>(__TAURI_INVOKE("day_set", { input })),
	/**  "Wake up": records now. The page decides which local date that is. */
	dayWakeNow: (date: string, utcOffsetMin: number) => typedError<Day, CommandError>(__TAURI_INVOKE("day_wake_now", { date, utcOffsetMin })),
	/**  "Go to sleep": records now and stops the running timer. */
	daySleepNow: (date: string, utcOffsetMin: number) => typedError<Day, CommandError>(__TAURI_INVOKE("day_sleep_now", { date, utcOffsetMin })),
	/**  The wake/sleep item the tray should offer now (`null` outside both time windows). */
	traySetDayAction: (action: {
	kind: DayActionKind,
	/**  Local date of the day being woken into or slept out of. */
	date: string,
	utc_offset_min: number,
} | null) => __TAURI_INVOKE<void>("tray_set_day_action", { action }),
	/**  Shows a warning sheet on the window; `true` if the user chose `confirm_label`. */
	dialogConfirm: (title: string, message: string, confirmLabel: string, cancelLabel: string) => __TAURI_INVOKE<boolean>("dialog_confirm", { title, message, confirmLabel, cancelLabel }),
	/**  Shows an informational sheet with a single button. */
	dialogAlert: (title: string, message: string, okLabel: string) => __TAURI_INVOKE<void>("dialog_alert", { title, message, okLabel }),
};

/** Events */
export const events = {
	dataChanged: makeEvent<DataChanged>("data-changed"),
	overlayEditing: makeEvent<OverlayEditing>("overlay-editing"),
	settingChanged: makeEvent<SettingChanged>("setting-changed"),
};

/* Types */
export type Activity = {
	id: string,
	name: string,
	color: ActivityColor,
	symbol: string | null,
	sort: number,
	archived_at: number | null,
	/**  `None` = top level. Sub-activities are one level deep and always take their parent's color. */
	parent_id: string | null,
};

/**  The fixed activity palette (rebuild-plan 4.3). Stored by name; hex lives in tokens.css. */
export type ActivityColor = "blue" | "green" | "orange" | "pink" | "purple" | "teal" | "yellow" | "gray";

/**
 *  Create (`id: None`) or update an activity. `sort: None` appends on create and keeps the current value
 *  on update. For a sub-activity, `color` is ignored: it is copied from the parent.
 */
export type ActivityInput = {
	id: string | null,
	name: string,
	color: ActivityColor,
	symbol: string | null,
	sort: number | null,
	parent_id: string | null,
};

export type AppInfo = {
	version: string,
	schema_version: number,
	db_path: string,
};

/**  A card's frame inside the overlay window, in logical px from the top-left. */
export type CardFrame = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**  Error returned to the frontend: a code for the UI plus the developer-facing message. */
export type CommandError = {
	code: ErrorCode,
	message: string,
};

/**  Activities or sessions changed; views should refetch. */
export type DataChanged = null;

/**  Inclusive range of 'YYYY-MM-DD' dates. */
export type DateRange = {
	from: string,
	to: string,
};

/**  A day is keyed by the local date of its wake-up; `sleep_ms` may fall after midnight. */
export type Day = {
	date: string,
	/**  `None` = fall back to the default wake-up time from Settings. */
	wake_ms: number | null,
	/**  `None` = still awake (or fall back to the default bedtime). */
	sleep_ms: number | null,
	/**  Minutes east of UTC on that day, so history can show that day's local clock times. */
	utc_offset_min: number,
};

/**
 *  Which wake/sleep item the tray offers right now. The page computes it, because the time windows
 *  depend on the local clock and Rust has no time zone database.
 */
export type DayAction = {
	kind: DayActionKind,
	/**  Local date of the day being woken into or slept out of. */
	date: string,
	utc_offset_min: number,
};

export type DayActionKind = "wake" | "sleep";

export type DayInput = {
	date: string,
	wake_ms: number | null,
	sleep_ms: number | null,
	utc_offset_min: number,
};

/**  Stable reason the frontend can turn into a localized message. */
export type ErrorCode = "invalid" | "not_found" | "overlap" | "in_use" | "database" | "file" | "internal";

export type ImportReport = {
	activity: TableCounts,
	session: TableCounts,
	plan: TableCounts,
	journal: TableCounts,
	day: TableCounts,
};

/**  One journal per day. Sync could leave two live rows for a date; reads take the newest. */
export type Journal = {
	id: string,
	date: string,
	text: string,
};

/**  One occurrence of a recurring plan on a local date, as absolute times. */
export type Occurrence = {
	plan_id: string,
	date: string,
	start_ms: number,
	end_ms: number,
};

/**  The overlay entered or left position-editing mode. */
export type OverlayEditing = boolean;

export type Plan = {
	id: string,
	activity_id: string,
	/**  The day of a one-off plan, or the first day a recurring plan applies. */
	date: string,
	start_hm: string,
	end_hm: string,
	/**  `None` = one-off; `"weekly:1,3,5"` = Monday, Wednesday, Friday (ISO weekdays, 1 = Monday). */
	rule: string | null,
	/**  Recurring plans only: log a session when an occurrence ends (rebuild-plan 10 F). */
	auto_log: boolean,
	/**  Recurring plans only: last day (inclusive); `None` = repeats forever. */
	until: string | null,
};

export type PlanInput = {
	id: string | null,
	activity_id: string,
	date: string,
	start_hm: string,
	end_hm: string,
	rule: string | null,
	auto_log: boolean,
	until: string | null,
};

export type Session = {
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
	/**  Set when the session was logged automatically from a recurring plan. */
	plan_id: string | null,
};

/**  Create (`id: None`) or edit a finished session. Running sessions are only created through `start`. */
export type SessionInput = {
	id: string | null,
	activity_id: string,
	start_ms: number,
	end_ms: number | null,
	note: string | null,
};

/**  A local setting was written; windows that depend on it should re-read. */
export type SettingChanged = {
	key: string,
};

/**  Per-table counts shown to the user after an import. */
export type TableCounts = {
	added: number,
	updated: number,
	/**  Already present with an equal or newer `updated_ms`. */
	unchanged: number,
};

/**  Half-open `[from_ms, to_ms)`. The frontend computes day/week bounds in the system time zone. */
export type TimeRange = {
	from_ms: number,
	to_ms: number,
};

/**  At most one of the two is set. */
export type TimerState = {
	running: Session | null,
	paused: Session | null,
};

/**
 *  Menu labels, supplied by the frontend so every string stays in the i18next locale files.
 *  `resume` may contain `{name}`, replaced with the paused activity's name.
 */
export type TrayStrings = {
	pause: string,
	resume: string,
	stop: string,
	no_activities: string,
	unknown_activity: string,
	open: string,
	quit: string,
	wake: string,
	sleep: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

