// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
	settingGet: (key: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("setting_get", { key })),
	settingSet: (key: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("setting_set", { key, value })),
	activityList: (includeArchived: boolean) => typedError<Activity[], CommandError>(__TAURI_INVOKE("activity_list", { includeArchived })),
	activityUpsert: (input: ActivityInput) => typedError<Activity, CommandError>(__TAURI_INVOKE("activity_upsert", { input })),
	activityArchive: (id: string, archived: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("activity_archive", { id, archived })),
	/**  Persists a new order; `ids` lists activities top to bottom. */
	activityReorder: (ids: string[]) => typedError<null, CommandError>(__TAURI_INVOKE("activity_reorder", { ids })),
	sessionStart: (activityId: string) => typedError<Session, CommandError>(__TAURI_INVOKE("session_start", { activityId })),
	sessionPause: () => typedError<{
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
} | null, CommandError>(__TAURI_INVOKE("session_pause")),
	sessionResume: () => typedError<Session, CommandError>(__TAURI_INVOKE("session_resume")),
	sessionStop: () => typedError<{
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
} | null, CommandError>(__TAURI_INVOKE("session_stop")),
	sessionCurrent: () => typedError<TimerState, CommandError>(__TAURI_INVOKE("session_current")),
	/**  Sessions overlapping the range, including a running one. */
	sessionList: (range: TimeRange) => typedError<Session[], CommandError>(__TAURI_INVOKE("session_list", { range })),
	sessionUpsert: (input: SessionInput) => typedError<Session, CommandError>(__TAURI_INVOKE("session_upsert", { input })),
	sessionDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("session_delete", { id })),
	traySetStrings: (strings: TrayStrings) => __TAURI_INVOKE<void>("tray_set_strings", { strings }),
	/**  Shows the tray's timer menu below the main window's timer button (logical px). */
	timerMenuPopup: (x: number, y: number) => typedError<null, CommandError>(__TAURI_INVOKE("timer_menu_popup", { x, y })),
	overlayShow: () => typedError<null, CommandError>(__TAURI_INVOKE("overlay_show")),
	overlayHide: () => typedError<null, CommandError>(__TAURI_INVOKE("overlay_hide")),
	/**  `true` lifts the overlay so it can be dragged; `false` saves the position and sinks it back. */
	overlaySetEditing: (editing: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("overlay_set_editing", { editing })),
	overlayResetPosition: () => typedError<null, CommandError>(__TAURI_INVOKE("overlay_reset_position")),
	/**  Called by the overlay page whenever its cards move or resize. */
	overlayLayout: (cards: CardFrame[]) => typedError<null, CommandError>(__TAURI_INVOKE("overlay_layout", { cards })),
	/**  One-off plans in the range plus recurring plans that have started; the frontend expands occurrences. */
	planList: (range: DateRange) => typedError<Plan[], CommandError>(__TAURI_INVOKE("plan_list", { range })),
	planUpsert: (input: PlanInput) => typedError<Plan, CommandError>(__TAURI_INVOKE("plan_upsert", { input })),
	planDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("plan_delete", { id })),
	journalList: (range: DateRange) => typedError<Journal[], CommandError>(__TAURI_INVOKE("journal_list", { range })),
	/**  Saves the day's entry; blank text removes it and returns `null`. */
	journalUpsert: (date: string, text: string) => typedError<{
	id: string,
	date: string,
	text: string,
} | null, CommandError>(__TAURI_INVOKE("journal_upsert", { date, text })),
	journalDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("journal_delete", { id })),
	/**  Opens a save panel (attached to the window) and writes every live record. `None` if cancelled. */
	dataExport: (defaultName: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("data_export", { defaultName })),
	/**  Opens a file panel and merges the chosen export into the database. `None` if cancelled. */
	dataImport: () => typedError<{
	activity: TableCounts,
	session: TableCounts,
	plan: TableCounts,
	journal: TableCounts,
} | null, CommandError>(__TAURI_INVOKE("data_import")),
};

/** Events */
export const events = {
	dataChanged: makeEvent<DataChanged>("data-changed"),
	overlayEditing: makeEvent<OverlayEditing>("overlay-editing"),
	settingChanged: makeEvent<SettingChanged>("setting-changed"),
};

/* Types */
export type Activity = {
	id: string,
	name: string,
	color: ActivityColor,
	symbol: string | null,
	sort: number,
	archived_at: number | null,
	/**  `None` = top level. Sub-activities are one level deep and always take their parent's color. */
	parent_id: string | null,
};

/**  The fixed activity palette (rebuild-plan 4.3). Stored by name; hex lives in tokens.css. */
export type ActivityColor = "blue" | "green" | "orange" | "pink" | "purple" | "teal" | "yellow" | "gray";

/**
 *  Create (`id: None`) or update an activity. `sort: None` appends on create and keeps the current value
 *  on update. For a sub-activity, `color` is ignored: it is copied from the parent.
 */
export type ActivityInput = {
	id: string | null,
	name: string,
	color: ActivityColor,
	symbol: string | null,
	sort: number | null,
	parent_id: string | null,
};

export type AppInfo = {
	version: string,
	schema_version: number,
	db_path: string,
};

/**  A card's frame inside the overlay window, in logical px from the top-left. */
export type CardFrame = {
	x: number | null,
	y: number | null,
	width: number | null,
	height: number | null,
};

/**  Error returned to the frontend as a plain message string. */
export type CommandError = string;

/**  Activities or sessions changed; views should refetch. */
export type DataChanged = null;

/**  Inclusive range of 'YYYY-MM-DD' dates. */
export type DateRange = {
	from: string,
	to: string,
};

export type ImportReport = {
	activity: TableCounts,
	session: TableCounts,
	plan: TableCounts,
	journal: TableCounts,
};

/**  One journal per day. Sync could leave two live rows for a date; reads take the newest. */
export type Journal = {
	id: string,
	date: string,
	text: string,
};

/**  The overlay entered or left position-editing mode. */
export type OverlayEditing = boolean;

export type Plan = {
	id: string,
	activity_id: string,
	/**  The day of a one-off plan, or the first day a recurring plan applies. */
	date: string,
	start_hm: string,
	end_hm: string,
	/**  `None` = one-off; `"weekly:1,3,5"` = Monday, Wednesday, Friday (ISO weekdays, 1 = Monday). */
	rule: string | null,
};

export type PlanInput = {
	id: string | null,
	activity_id: string,
	date: string,
	start_hm: string,
	end_hm: string,
	rule: string | null,
};

export type Session = {
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
};

/**  Create (`id: None`) or edit a finished session. Running sessions are only created through `start`. */
export type SessionInput = {
	id: string | null,
	activity_id: string,
	start_ms: number,
	end_ms: number | null,
	note: string | null,
};

/**  A local setting was written; windows that depend on it should re-read. */
export type SettingChanged = {
	key: string,
};

/**  Per-table counts shown to the user after an import. */
export type TableCounts = {
	added: number,
	updated: number,
	/**  Already present with an equal or newer `updated_ms`. */
	unchanged: number,
};

/**  Half-open `[from_ms, to_ms)`. The frontend computes day/week bounds in the system time zone. */
export type TimeRange = {
	from_ms: number,
	to_ms: number,
};

/**  At most one of the two is set. */
export type TimerState = {
	running: Session | null,
	paused: Session | null,
};

/**
 *  Menu labels, supplied by the frontend so every string stays in the i18next locale files.
 *  `resume` may contain `{name}`, replaced with the paused activity's name.
 */
export type TrayStrings = {
	pause: string,
	resume: string,
	stop: string,
	no_activities: string,
	unknown_activity: string,
	open: string,
	quit: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

