// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	appInfo: () => typedError<AppInfo, CommandError>(__TAURI_INVOKE("app_info")),
	settingGet: (key: string) => typedError<string | null, CommandError>(__TAURI_INVOKE("setting_get", { key })),
	settingSet: (key: string, value: string) => typedError<null, CommandError>(__TAURI_INVOKE("setting_set", { key, value })),
	activityList: (includeArchived: boolean) => typedError<Activity[], CommandError>(__TAURI_INVOKE("activity_list", { includeArchived })),
	activityUpsert: (input: ActivityInput) => typedError<Activity, CommandError>(__TAURI_INVOKE("activity_upsert", { input })),
	activityArchive: (id: string, archived: boolean) => typedError<null, CommandError>(__TAURI_INVOKE("activity_archive", { id, archived })),
	sessionStart: (activityId: string) => typedError<Session, CommandError>(__TAURI_INVOKE("session_start", { activityId })),
	sessionPause: () => typedError<{
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
} | null, CommandError>(__TAURI_INVOKE("session_pause")),
	sessionResume: () => typedError<Session, CommandError>(__TAURI_INVOKE("session_resume")),
	sessionStop: () => typedError<{
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
} | null, CommandError>(__TAURI_INVOKE("session_stop")),
	sessionCurrent: () => typedError<TimerState, CommandError>(__TAURI_INVOKE("session_current")),
	/**  Sessions overlapping the range, including a running one. */
	sessionList: (range: TimeRange) => typedError<Session[], CommandError>(__TAURI_INVOKE("session_list", { range })),
	sessionUpsert: (input: SessionInput) => typedError<Session, CommandError>(__TAURI_INVOKE("session_upsert", { input })),
	sessionDelete: (id: string) => typedError<null, CommandError>(__TAURI_INVOKE("session_delete", { id })),
	traySetStrings: (strings: TrayStrings) => __TAURI_INVOKE<void>("tray_set_strings", { strings }),
	/**  Shows the tray's timer menu below the main window's timer button (logical px). */
	timerMenuPopup: (x: number, y: number) => typedError<null, CommandError>(__TAURI_INVOKE("timer_menu_popup", { x, y })),
};

/** Events */
export const events = {
	dataChanged: makeEvent<DataChanged>("data-changed"),
};

/* Types */
export type Activity = {
	id: string,
	name: string,
	color: ActivityColor,
	symbol: string | null,
	sort: number,
	archived_at: number | null,
};

/**  The fixed activity palette (rebuild-plan 4.3). Stored by name; hex lives in tokens.css. */
export type ActivityColor = "blue" | "green" | "orange" | "pink" | "purple" | "teal" | "yellow" | "gray";

/**  Create (`id: None`) or update an activity. `sort: None` appends on create and keeps the current value on update. */
export type ActivityInput = {
	id: string | null,
	name: string,
	color: ActivityColor,
	symbol: string | null,
	sort: number | null,
};

export type AppInfo = {
	version: string,
	schema_version: number,
	db_path: string,
};

/**  Error returned to the frontend as a plain message string. */
export type CommandError = string;

/**  Activities or sessions changed; views should refetch. */
export type DataChanged = null;

export type Session = {
	id: string,
	activity_id: string,
	start_ms: number,
	/**  `None` while running. */
	end_ms: number | null,
	note: string | null,
	continues_id: string | null,
};

/**  Create (`id: None`) or edit a finished session. Running sessions are only created through `start`. */
export type SessionInput = {
	id: string | null,
	activity_id: string,
	start_ms: number,
	end_ms: number | null,
	note: string | null,
};

/**  Half-open `[from_ms, to_ms)`. The frontend computes day/week bounds in the system time zone. */
export type TimeRange = {
	from_ms: number,
	to_ms: number,
};

/**  At most one of the two is set. */
export type TimerState = {
	running: Session | null,
	paused: Session | null,
};

/**
 *  Menu labels, supplied by the frontend so every string stays in the i18next locale files.
 *  `resume` may contain `{name}`, replaced with the paused activity's name.
 */
export type TrayStrings = {
	pause: string,
	resume: string,
	stop: string,
	no_activities: string,
	unknown_activity: string,
	open: string,
	quit: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

