#!/bin/sh
# Writes apple/Config/Supabase.generated.xcconfig (git-ignored) from SUPABASE_URL / SUPABASE_ANON_KEY,
# taken from the environment first (CI), then from the repository's root .env — the same sources as the
# desktop's src-tauri/build.rs. Run it after creating or editing .env.
#
#   --check   (used by the Xcode build phase) regenerate, and fail the build if the file changed, because
#             Xcode read the old values before this script ran. Building again picks up the new ones.
set -eu

here=$(cd "$(dirname "$0")" && pwd)
root=$(cd "$here/../.." && pwd)
out="$here/../Config/Supabase.generated.xcconfig"

# Last assignment of KEY in .env, with `export`, quotes and surrounding spaces removed.
from_dotenv() {
  [ -f "$root/.env" ] || return 0
  sed -n "s/^[[:space:]]*\(export[[:space:]]\{1,\}\)\{0,1\}$1[[:space:]]*=[[:space:]]*//p" "$root/.env" \
    | tail -n 1 | sed -e 's/[[:space:]]*$//' -e 's/^"\(.*\)"$/\1/' -e "s/^'\(.*\)'\$/\1/"
}

url=${SUPABASE_URL:-}
key=${SUPABASE_ANON_KEY:-}
[ -n "$url" ] || url=$(from_dotenv SUPABASE_URL)
[ -n "$key" ] || key=$(from_dotenv SUPABASE_ANON_KEY)
url=${url%/}

# `//` starts a comment in an xcconfig, so the URL's slashes are split with an empty variable.
escaped=$(printf '%s' "$url" | sed 's#//#/$()/#g')

content="// Generated by apple/scripts/configure-supabase.sh from the root .env. Do not edit or commit.
SUPABASE_URL = $escaped
SUPABASE_ANON_KEY = $key"

if [ -z "$url" ] && [ -z "$key" ] && [ ! -f "$out" ]; then
  # Nothing configured and nothing generated: a local-only build, nothing to do.
  exit 0
fi

if [ -f "$out" ] && [ "$(cat "$out")" = "$content" ]; then
  exit 0
fi

printf '%s\n' "$content" > "$out"
if [ -n "$url" ]; then echo "Supabase config written for $url"; else echo "Supabase config cleared (local-only build)"; fi

if [ "${1:-}" = "--check" ]; then
  echo "error: apple/Config/Supabase.generated.xcconfig was out of date and has been regenerated from .env. Build again to use it."
  exit 1
fi
